alter table CUBACASSALAST_STATION add constraint FK_CUBACASSALAST_STATION_ON_ROUTE foreign key (ROUTE_ID) references CUBACASSALAST_ROUTE(ID);
create unique index IDX_CUBACASSALAST_STATION_UNIQ_NAME on CUBACASSALAST_STATION (NAME);
create index IDX_CUBACASSALAST_STATION_ON_ROUTE on CUBACASSALAST_STATION (ROUTE_ID);
