alter table CUBACASSALAST_TRAVEL add constraint FK_CUBACASSALAST_TRAVEL_ON_PASSENGER foreign key (PASSENGER_ID) references CUBACASSALAST_PASSENGER(ID);
create unique index IDX_CUBACASSALAST_TRAVEL_UNIQ_NUMBER_ on CUBACASSALAST_TRAVEL (NUMBER_);
create index IDX_CUBACASSALAST_TRAVEL_ON_PASSENGER on CUBACASSALAST_TRAVEL (PASSENGER_ID);
