-- begin CUBACASSALAST_TICKET
alter table CUBACASSALAST_TICKET add constraint FK_CUBACASSALAST_TICKET_ON_DEPARTURE_STATION foreign key (DEPARTURE_STATION_ID) references CUBACASSALAST_STATION(ID)^
alter table CUBACASSALAST_TICKET add constraint FK_CUBACASSALAST_TICKET_ON_ARRIVAL_STATION foreign key (ARRIVAL_STATION_ID) references CUBACASSALAST_STATION(ID)^
alter table CUBACASSALAST_TICKET add constraint FK_CUBACASSALAST_TICKET_ON_PASSENGER foreign key (PASSENGER_ID) references CUBACASSALAST_PASSENGER(ID)^
alter table CUBACASSALAST_TICKET add constraint FK_CUBACASSALAST_TICKET_ON_TRAVEL foreign key (TRAVEL_ID) references CUBACASSALAST_TRAVEL(ID)^
create index IDX_CUBACASSALAST_TICKET_ON_DEPARTURE_STATION on CUBACASSALAST_TICKET (DEPARTURE_STATION_ID)^
create index IDX_CUBACASSALAST_TICKET_ON_ARRIVAL_STATION on CUBACASSALAST_TICKET (ARRIVAL_STATION_ID)^
create index IDX_CUBACASSALAST_TICKET_ON_PASSENGER on CUBACASSALAST_TICKET (PASSENGER_ID)^
create index IDX_CUBACASSALAST_TICKET_ON_TRAVEL on CUBACASSALAST_TICKET (TRAVEL_ID)^
-- end CUBACASSALAST_TICKET
-- begin CUBACASSALAST_STATION
alter table CUBACASSALAST_STATION add constraint FK_CUBACASSALAST_STATION_ON_ROUTE foreign key (ROUTE_ID) references CUBACASSALAST_ROUTE(ID)^
create unique index IDX_CUBACASSALAST_STATION_UNIQ_NAME on CUBACASSALAST_STATION (NAME)^
create index IDX_CUBACASSALAST_STATION_ON_ROUTE on CUBACASSALAST_STATION (ROUTE_ID)^
-- end CUBACASSALAST_STATION
-- begin CUBACASSALAST_ROUTE
create unique index IDX_CUBACASSALAST_ROUTE_UNIQ_NUMBER_ on CUBACASSALAST_ROUTE (NUMBER_)^
-- end CUBACASSALAST_ROUTE
-- begin CUBACASSALAST_TRAVEL
alter table CUBACASSALAST_TRAVEL add constraint FK_CUBACASSALAST_TRAVEL_ON_PASSENGER foreign key (PASSENGER_ID) references CUBACASSALAST_PASSENGER(ID)^
create index IDX_CUBACASSALAST_TRAVEL_ON_PASSENGER on CUBACASSALAST_TRAVEL (PASSENGER_ID)^
-- end CUBACASSALAST_TRAVEL
-- begin CUBACASSALAST_STATION_STATION_LINK
alter table CUBACASSALAST_STATION_STATION_LINK add constraint FK_STASTA_ON_STATION_1 foreign key (STATION_1_ID) references CUBACASSALAST_STATION(ID)^
alter table CUBACASSALAST_STATION_STATION_LINK add constraint FK_STASTA_ON_STATION_2 foreign key (STATION_2_ID) references CUBACASSALAST_STATION(ID)^
-- end CUBACASSALAST_STATION_STATION_LINK
